services:
  backend:
    #image: oumaima158/Rest-backend:v4
    build:
      context: ./backend/laravel
      dockerfile: Dockerfile
    container_name: backend 
    ports:
      - "8000:80"
    volumes:
      - ./backend/php:/var/www/html 
      - vendor_data:/var/www/html/vendor
    depends_on:
      - mysql
    networks:
      - webapp
      
  frontend:
    #image: oumaima158/hotel-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
    - CHOKIDAR_USEPOLLING=true
    ports:
      - "4300:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - webapp

  mysql:
    #image: oumaima158/restaurant-mysql:v1
    build:
      context: ./mysql
      dockerfile: dockerfile
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webapp
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql  
      PMA_PORT: 3306
    ports:
      - "8080:80" 
    depends_on:
      - mysql
    networks:
      - webapp 
networks:
  webapp:
    driver: bridge

volumes:
  db_data:
  vendor_data:
